name: 'Release Docker'

on:
  workflow_run:
    workflows: ["Release Base"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Latest Package job

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry (ghcr)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Get version
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV

    - name: Publish Latest Package
      uses: docker/build-push-action@v4
      if: github.ref == 'refs/heads/master'
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7 # 你准备构建的镜像平台
        push: true
        tags: ghcr.io/qd-today/qd:latest,docker.io/qdtoday/qd:${{ env.version }}
